name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      !(contains(github.event.pull_request.head.ref, 'main')
        || contains(github.event.pull_request.head.ref, 'master')
        || contains(github.event.pull_request.head.ref, 'dev')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          echo "Deleting branch..."
          echo "Repository: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"
          echo "Token: ${{ secrets.GITHUB_TOKEN }}"
          
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.event.pull_request.head.repo.full_name }}/git/refs/heads/${{ github.event.pull_request.head.ref }}"